"""A batch detaches the way a single run does (§3.5.3, ARCH §"Parallel runs").

A cross product used to be the one `bench run` invocation that held the terminal: the
detach branch sat *after* the batch branch returned, so `--foreground` was silently
ignored and a closed lid killed every run in the batch. The reason detaching exists —
a run is measured in hours — applies harder to several of them at once.

What detaches is a **supervisor**, not each job. Detaching the jobs individually would
release `run_jobs`' per-system lock the instant each child was launched, so two runs
against one system could overlap and quietly contaminate the latency and rank-stability
metrics (§7.4, §7.5). One detached supervisor keeps that lock doing its job while the
launching terminal goes free.

`--limit 0` throughout: these runs plan no questions, so a detached child — which is a
fresh process that `conftest`'s offline transport does not patch — makes no model call.
"""

import shutil
import time
from pathlib import Path

import pytest

from orchestrator.cli import main
from orchestrator.runstate import read_state, resolve_status

REPO = Path(__file__).resolve().parents[2]
FIXTURES = REPO / "tests" / "datasets" / "fixtures"


@pytest.fixture
def datasets(tmp_path: Path) -> Path:
    dest = tmp_path / "datasets"
    shutil.copytree(FIXTURES, dest)
    return dest


def batch_argv(datasets: Path, artifacts: Path, systems: str, sets: str, *extra: str) -> list[str]:
    return [
        "run",
        systems,
        "--dataset",
        sets,
        "--limit",
        "0",
        "--suite",
        "v1",
        "--artifacts",
        str(artifacts),
        "--datasets",
        str(datasets),
        "--repo-root",
        str(REPO),
        *extra,
    ]


def await_runs(artifacts: Path, run_ids: list[str], timeout_s: float = 120.0) -> list[str]:
    """Block until every id has settled, then return their statuses.

    Polling, because the launcher returns before the supervisor has written anything —
    which is what detaching means.
    """
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        states = [read_state(artifacts / run_id) for run_id in run_ids]
        if all(s is not None and s.status in ("done", "failed") for s in states):
            return [resolve_status(s) for s in states if s is not None]
        time.sleep(0.05)
    raise AssertionError(f"runs {run_ids} did not finish within {timeout_s}s")


def printed_ids(out: str) -> list[str]:
    """Return the run ids printed as `<id>  <system>  <dataset>`, one per job.

    Every id is printed before the first `===` report header, so the listing stops there.
    Matching on shape alone would also catch a report row like `accuracy  0.000  ...`.
    """
    ids = []
    for line in out.splitlines():
        if line.startswith("==="):
            break
        fields = line.split()
        if len(fields) == 3:
            ids.append(fields[0])
    return ids


def test_a_multi_system_batch_returns_without_waiting(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """The launcher's job is to start the batch, not to sit through it."""
    artifacts = tmp_path / "artifacts"
    assert main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many")) == 0
    assert "detached" in capsys.readouterr().err.lower()


def test_the_launcher_prints_every_run_id_before_detaching(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A batch interrupted later is only resumable by ids the user has already seen.

    The supervisor cannot print them: its stdout goes nowhere once detached. So the ids
    are generated by the launcher and handed down, rather than each child inventing one.
    """
    artifacts = tmp_path / "artifacts"
    main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many"))
    out = capsys.readouterr().out
    assert len(printed_ids(out)) == 2
    assert "bm25" in out
    assert "no_memory" in out


def test_the_detached_batch_actually_runs_every_job(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Detaching must not mean dropping: both runs finish under the printed ids."""
    artifacts = tmp_path / "artifacts"
    main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many"))
    ids = printed_ids(capsys.readouterr().out)
    assert await_runs(artifacts, ids) == ["done", "done"]
    for run_id in ids:
        assert (artifacts / run_id / "report.json").is_file()


def test_the_ids_the_launcher_printed_are_the_ids_that_ran(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """A supervisor that generated its own ids would strand the ones already printed."""
    artifacts = tmp_path / "artifacts"
    main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many"))
    ids = printed_ids(capsys.readouterr().out)
    await_runs(artifacts, ids)
    assert sorted(p.name for p in artifacts.iterdir() if p.is_dir()) == sorted(ids)


def test_foreground_still_blocks_and_prints_the_report_rows(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """`--foreground` is the opt-in that keeps the aggregated table a batch used to give."""
    artifacts = tmp_path / "artifacts"
    assert (
        main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many", "--foreground")) == 0
    )
    out = capsys.readouterr().out
    assert "===" in out, "a blocking batch prints each child's row"
    for run_id in printed_ids(out):
        assert (artifacts / run_id / "report.json").is_file()


def test_a_single_run_is_unaffected(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """One system and one dataset is not a batch, and already detached correctly."""
    artifacts = tmp_path / "artifacts"
    assert main(batch_argv(datasets, artifacts, "bm25", "fixture_many")) == 0
    err = capsys.readouterr().err.lower()
    assert "detached" in err
    assert "bench logs" in err, "a single run names the log command for its one id"


def test_a_usage_error_is_reported_before_anything_detaches(
    datasets: Path, tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Validation happens on the command the user typed, not unseen inside a supervisor."""
    artifacts = tmp_path / "artifacts"
    code = main(batch_argv(datasets, artifacts, "bm25,no_memory", "fixture_many", "--resume", "x"))
    assert code == 2
    assert not artifacts.exists() or not any(artifacts.iterdir())
